### ISSUE TITLE
What is the difference between LMFlow and huggingface/peft libraries？

### ISSUE THREAD

**Issue by yanni-code** [OptimalScale/LMFlow#101]
What is the difference between LMFlow and huggingface/peft libraries？

**Comment by research4pan** [comment]
Thanks for your attention! PEFT is a package with collection of Parameter-Efficient Fine-Tuning (PEFT) methods, while LMFlow is a framework for finetuning/inferencing large models. In other words, normally users use PEFT to improve their own training/inference process, as **a component of the process**, while users mainly use our package to directly train/inference/build pipelines, **based on our framework**.

Since LMFlow focus on the whole training/inference process, we adopt several tuning methods, **including PEFT**, to improve the finetuning process. Hope that answers your question. If you have any other questions, please don't hesitate to let us know. Thanks 😄

**Comment by yanni-code** [comment]
Thank you very much for your answers and your great work！
