### ISSUE TITLE
run run_chatbot.sh RuntimeError: Tensors must be contiguous

### ISSUE THREAD

**Issue by shenmadouyaowen** [OptimalScale/LMFlow#144]
Hello, I downloaded the gpt-neo-2.7B model and ran run_chatbot.sh, which displayed the following error? How can I resolve it?
```
(lmflow) root@shenma:~/LMFlow# ./scripts/run_chatbot.sh output_models/gpt-neo-2.7B
[2023-04-06 09:55:55,760] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0: setting --include=localhost:0
[2023-04-06 09:55:55,769] [INFO] [runner.py:550:main] cmd = /root/anaconda3/envs/lmflow/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None examples/chatbot.py --deepspeed configs/ds_config_chatbot.json --model_name_or_path output_models/gpt-neo-2.7B
[2023-04-06 09:55:56,692] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
[2023-04-06 09:55:56,692] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-04-06 09:55:56,692] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-04-06 09:55:56,692] [INFO] [launch.py:162:main] dist_world_size=1
[2023-04-06 09:55:56,692] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0
Traceback (most recent call last):
  File "/root/LMFlow/examples/chatbot.py", line 117, in <module>
    main()
  File "/root/LMFlow/examples/chatbot.py", line 44, in main
    model = AutoModel.get_model(
  File "/root/LMFlow/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/root/LMFlow/src/lmflow/models/hf_decoder_model.py", line 224, in __init__
    self.ds_engine = deepspeed.initialize(model=self.backend_model, config_params=ds_config)[0]
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 297, in __init__
    self._configure_distributed_model(model)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1182, in _configure_distributed_model
    self._broadcast_model()
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1105, in _broadcast_model
    dist.broadcast(p,
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 123, in log_wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 228, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 78, in broadcast
    return torch.distributed.broadcast(tensor=tensor,
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1555, in broadcast
    work = group.broadcast([tensor], opts)
RuntimeError: Tensors must be contiguous
[2023-04-06 09:56:28,731] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 439575
[2023-04-06 09:56:28,731] [ERROR] [launch.py:324:sigkill_handler] ['/root/anaconda3/envs/lmflow/bin/python', '-u', 'examples/chatbot.py', '--local_rank=0', '--deepspeed', 'configs/ds_config_chatbot.json', '--model_name_or_path', 'output_models/gpt-neo-2.7B'] exits with return code = 1
```
`deepspeed                0.8.3`

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! As the chatbot works fine in [Google Colab]((https://colab.research.google.com/drive/1P9Hf6_mLE7WHH92pw73j9D5kz6GTdkow?usp=sharing)), it is possible this is caused by some local incompatibility problems. Someone has reported similar issues when using huggingface transformers. It appears to be a problem of deepspeed. One way to walk around is to make sure every tensor is continuous right after model initialization, as recommended in [this link](https://github.com/huggingface/transformers/issues/21183#issuecomment-1399721031).
```
for p in model.backend_model().parameters():
    p = p.contiguous()
```

It you don't want to modify the code and simply want to have a try, we recommend to run this experiment on [Google Colab](https://colab.research.google.com/drive/1P9Hf6_mLE7WHH92pw73j9D5kz6GTdkow?usp=sharing), which has the environment set up for you. You may also try [docker](https://github.com/OptimalScale/LMFlow/tree/main/docker), which has much less dependency problems.

Hope that can resolve your issue. Thanks 😄

**Comment by shenmadouyaowen** [comment]
Thank you. I also found this solution on Google, but I cannot solve it

**Comment by shenmadouyaowen** [comment]
I still encountered this error using the Docker version
#system
Ubuntu 20.04.5 LTS x86_64
#Graphics card
NVIDIA GeForce RTX 3060

**Comment by research4pan** [comment]
If the docker version doesn't work, it is highly possible that it was caused by some hardware dependency problems. Could you please provide your CUDA version and CUDA driver version, so we may check that for you? Also, it would be nice if you could try on some small models and check if the problem occurs as well. Thanks!

**Comment by george66s** [comment]
Hi, I made the changes according to your suggestion. But issue is still there. Below are changes I have made to the code.

src/lmflow/models/hf_decoder_model.py, starting from line 198:

            ##### George: modified to deal with the issue of Tensors must be contiguous according to issue 144
            model = self.backend_model
            for p in model.parameters():
                p = p.contiguous()
            self.ds_engine = deepspeed.initialize(model=model, config_params=ds_config)[0]
            ##### George: end modification

deepspeed.initialize(model=model, config_params=ds_config)[0] still comes back with error message: Tensors must be contiguous

Is above modification correct?

Thanks
George

**Comment by george66s** [comment]
By the way, below is my hardware and conda env:

Driver Version: 510.108.03   CUDA Version: 11.6

name: lmflow
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py39hfc96bbd_0
  - mpich=3.3.2=hc856adb_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py39h06a4308_0
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.17.1
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==22.2.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cmake==3.26.0
    - datasets==2.10.1
    - deepspeed==0.8.3+e73de8ce
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - filelock==3.10.0
    - flask==2.2.3
    - flask-cors==3.0.10
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - hjson==3.1.0
    - huggingface-hub==0.13.2
    - idna==3.4
    - importlib-metadata==6.1.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - lit==15.0.7
    - markupsafe==2.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - networkx==3.0
    - ninja==1.11.1
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - packaging==23.0
    - pandas==1.5.3
    - pathtools==0.1.2
    - peft==0.3.0.dev0
    - protobuf==4.22.1
    - psutil==5.9.4
    - py-cpuinfo==9.0.0
    - pyarrow==11.0.0
    - pydantic==1.10.6
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - responses==0.18.0
    - sentencepiece==0.1.97
    - sentry-sdk==1.17.0
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - sympy==1.11.1
    - tokenizers==0.13.2
    - torch==2.0.0
    - tqdm==4.65.0
    - transformers==4.28.0.dev0
    - triton==2.0.0
    - trl==0.4.2.dev0
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - wandb==0.14.0
    - werkzeug==2.2.3
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.15.0

**Comment by research4pan** [comment]
Thanks! Could you check if the following code piece works?
```
for p in model.parameters():
    p.data.copy_(p.contiguous().data)
```
I checked that the aforementioned code may not be able to replace the original parameters, this one may work. According to [pytorch's official documentation](https://pytorch.org/docs/stable/generated/torch.Tensor.contiguous.html), `p.contiguous()` only returns a memory-contiguous tensor, but may not affect the original tensor.

Also, it would be nice if you can check the problem when running on smaller models. I am wondering if that's related to model size. Thanks!

**Comment by george66s** [comment]
The above changed code still not working. It works when using gpt2 as the model.

**Comment by research4pan** [comment]
Hi, I meet a similar problem when the remaining GPU memory is not sufficient. My guess is that RAM optimized load splits tensors and moves its around in different GPUs, thus triggers the error. You may try to add `--use_ram_optimized_load` in `scripts/chatbot.sh` to see if the problem is resolved. Thanks 😄

**Comment by shenmadouyaowen** [comment]
> 
Hello, here are my cuda and cuda driver versions
```
NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6 
```

**Comment by research4pan** [comment]
I think that it is highly probable that the problem is caused by RAM optimized load. Since small models don't have this issue, it is  possible that `gpt-neo-2.7B` triggers the RAM optimize mechanism and results in model splits among different devices, then leads to this error. You may turn off this RAM optimization via adding `--use_ram_optimized_load False`  in `scripts/chatbot.sh` to see if the problem can be resolved. Thanks 😄

**Comment by shenmadouyaowen** [comment]
> I think that it is highly probable that the problem is caused by RAM optimized load. Since small models don't have this issue, it is possible that `gpt-neo-2.7B` triggers the RAM optimize mechanism and results in model splits among different devices, then leads to this error. You may turn off this RAM optimization via adding `--use_ram_optimized_load False` in `scripts/chatbot.sh` to see if the problem can be resolved. Thanks 😄

Thank you for your reply. This will directly kill the program

**Comment by research4pan** [comment]
I think the bottleneck here is RAM. Normally a setup similar to our Google Colab example should work, which has approximately  13G RAM and 16G GPU memory (T4). May I ask how much RAM there is in your server? Thanks!

**Comment by research4pan** [comment]
Thanks for providing more details! Looks like the problem was caused by multiple factors. Since loading gpt-neo-2.7B requires more than 16GB memory during the loading process, turning on RAM optimized loading becomes necessary. However, this option will result in splits of model tensors when the GPU memory is not enough, which leads to the Runtime Error here `Tensors must be continguous`.

To avoid this error, there are several options:
- You may add more RAM to your machine/server, and turn off `--use_ram_optimized_load False`.
- You may use a GPU with larger GPU memory, 16G will be sufficient.
- You may use a CPU-only server with large RAM and run `./scripts/run_chatbot_cpu.sh`, which supports CPU-only inference (although the speed may be much slower when compared with GPU).

We recommend Google Colab for running this type of experiments. Hope that answers your question. Thanks 😄

**Comment by shenmadouyaowen** [comment]
> Thanks for providing more details! Looks like the problem was caused by multiple factors. Since loading gpt-neo-2.7B requires more than 16GB memory during the loading process, turning on RAM optimized loading becomes necessary. However, this option will result in splits of model tensors when the GPU memory is not enough, which leads to the Runtime Error here `Tensors must be continguous`.
> 
> To avoid this error, there are several options:
> 
> * You may add more RAM to your machine/server, and turn off `--use_ram_optimized_load False`.
> * You may use a GPU with larger GPU memory, 16G will be sufficient.
> * You may use a CPU-only server with large RAM and run `./scripts/run_chatbot_cpu.sh`, which supports CPU-only inference (although the speed may be much slower when compared with GPU).
> 
> We recommend Google Colab for running this type of experiments. Hope that answers your question. Thanks 😄

Okay, thank you. I closed the issue
