### ISSUE TITLE
Is it possible to use only CPU to run the chatbot?

### ISSUE THREAD

**Issue by vincent7f** [OptimalScale/LMFlow#198]
Fastchat supports to use parameter '--device cpu' to run without GPU. Do you support this kind of parameter is LMFlow? Or is there, somewhere in source code, that we could change a few codes to use only CPU? Thanks in advance.

**Comment by research4pan** [comment]
Thanks for your suggestion! We've added `./scripts/run_chatbot_cpu.sh` to support chatbot in CPU (currently only supported in Linux, for Windows & Mac one may need to install [gloo backend](https://pytorch.org/docs/stable/distributed.html#backends-that-come-with-pytorch) for torch distributed). For finetune and evaluation, since the time-consuming is already expensive, we haven't added this option yet. We may add CPU support for finetune if the demand is high in the future. Thanks 😄

**Comment by vincent7f** [comment]
Thanks for your update. That is exactly what I asked. But there mighe be bug.  Please have a check.

When running the new script './scripts/run_chatbot_cpu.sh', it showed error message (as captured in the last image: "AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'". After reading some codes, I found the root cause was in the file hf_decoder_model.py . In this file, library peft woudl be imported even no GPU should used. So I commented them and everything goes well. 

![image](https://user-images.githubusercontent.com/45114756/232069993-35b0e277-28fd-438b-bf71-7561b454270f.png)

![image](https://user-images.githubusercontent.com/45114756/232074068-f2093108-41b1-48d6-9bb9-b50d9a22e9a5.png)

**Comment by research4pan** [comment]
Thanks for pointing that out! It works fine when I did the test, so I miss that bug. I will try to add conditional import for that package soon. Thanks for your contribution 😄

**Comment by shizhediao** [comment]
Hi,
We have updated our code and removed unused import and kept the essential ones.
The current code should work well.

Thank you very much for your help!
