### ISSUE TITLE
I deployed the model locally with app.py. But it only answered 'There is something wrong, Please query again.'

### ISSUE THREAD

**Issue by snake-head** [OptimalScale/LMFlow#199]
![image](https://user-images.githubusercontent.com/62976678/230909914-9cdd18cd-6f7b-4f7c-90ea-9f0176433dfd.png)
![image](https://user-images.githubusercontent.com/62976678/230909958-7e36a205-5687-4b8e-a381-5b9d929e5d60.png)

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Looks like this is a problem related to `app.py` according to a  [similar issue](https://github.com/OptimalScale/LMFlow/issues/128#issuecomment-1501747677) raised before. You may try `deepspeed --num_gpus=1 app.py` to see if the problem still exists. Thanks 😄

**Comment by snake-head** [comment]
> Thanks for your interest in LMFlow! Looks like this is a problem related to `app.py` according to a [similar issue](https://github.com/OptimalScale/LMFlow/issues/128#issuecomment-1501747677) raised before. You may try `deepspeed --num_gpus=1 app.py` to see if the problem still exists. Thanks 😄

I tried the method you mentioned and solved the above problem. But the model always generates irrelevant answers.
![image](https://user-images.githubusercontent.com/62976678/231036348-53087570-6d1a-463a-83d8-d4714481c78c.png)
It seems that at the end of the answer, it will add 'Definition: Tuning the model with human instruction'.
I guess there were some issues with fine-tuning gpt-neo2.7B.

**Comment by research4pan** [comment]
Glad to hear that you solve the previous question~As for the issues related to the outputs of finetuned gpt-neo2.7B, it is caused by the old finetuning prompt we used, which has certain structures. As gpt-neo2.7B is a rather weak model, we strongly recommend you to further finetune the model or use larger models. We will also release new models with better performance in the future. Thanks 😄
