### ISSUE TITLE
why should json_data should have the same data type?

### ISSUE THREAD

**Issue by songtaoshi** [OptimalScale/LMFlow#2]
Hi, why "text_only" & "text2text" can not be trained simultaneously?

**Comment by songtaoshi** [comment]
@shizhediao

**Comment by research4pan** [comment]
Good question. Actually this is designed on purpose so that we can assure that input datasets are homogeneous in terms of their structures. This property is very useful in multiple scenarios:

- When you like to finetune a decoder-only model (like GPT2) and apply prompt engineering given the source datasets, e.g.
```
input, output -> "Input: {input}. Output: {output}"
```
Then accepting the processed "text-only" typed dataset would be more flexible since it allows you to apply any prompt engineering techniques to prepare the dataset.

- When the specified model has some special requirements on the input dataset. For example, encoder-decoder models (like T5, will be supported in the future) only accept "text2text" typed datasets.

**Comment by songtaoshi** [comment]
thanks for ur reply!   
but another difference may be that  when input is "text2text" type, the input is ignored in loss calculation, but "text_only" the whole input is calculated?

**Comment by songtaoshi** [comment]
@shizhediao @research4plan

**Comment by research4pan** [comment]
Yes, exactly! That's another great example to illustrate this difference 😄 . Decoder-only models, like GPT2, don't accept "text2text" typed dataset. To form an acceptable "text_only" typed dataset for decoder-only models, you may preprocess the data beforehand.

We plan to provide some useful tools in the future to facilitate this conversion between datasets.

**Comment by songtaoshi** [comment]
so actually Decoder-only models GPT2 can also accept "text2text"typed dataset, just reformat it to "text_only"  and  adjust the mask when loss calculation, using the input as context and calculate loss in output.   

So still the question can we simultaneously train "text2text" and "text_only" in one epoch?,    
-text_only, we normally calculate all tokens' loss
-text2text, we only calculate output tokens' loss 

@research4pan @shizhediao

**Comment by research4pan** [comment]
Currently we don't support that, but we will definitely consider it and improve our package in the future. Thanks for your suggestion! Also, if you would like to contribute, feel free to contact us. We can improve this package together 😄

**Comment by songtaoshi** [comment]
Thanks！
