### ISSUE TITLE
如何使用LMFlow训练自己的私有模型？

### ISSUE THREAD

**Issue by nuaa-wwbin** [OptimalScale/LMFlow#206]
我是一名计算机专业的学生，但也是一名机器学习的门外汉，我想咨询一下，我应该怎么应该如何使用LMFlow？如何利用LMFlow来训练自己的私有模型？用于训练的数据应该是什么格式的？是否有相关教程或者guide？

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! To use LMFlow, you may first obtain a Linux server with GPU equipped. We recommend Ubuntu 20.04, so that the setup will be most compatible with our settings. Then, following the guide in [setup](https://github.com/OptimalScale/LMFlow/blob/main/README.md#1setup), you can install the LMFlow package.

To have a first taste of LMFlow, you may try our [Google Colab demo](https://colab.research.google.com/drive/1P9Hf6_mLE7WHH92pw73j9D5kz6GTdkow?usp=sharing), which requires a Google Colab account. Google Colab provide free T4 GPUs for users, so you may directly run our chatbot (a rather weak version) on that.

After that, you may finetune your model via `scripts/run_finetune.sh`, which corresponds to [this section of README](https://github.com/OptimalScale/LMFlow/blob/main/README.md#3-run-scripts). You are free to modify our shell script, mainly modifying the used model `--model_name_or_path gpt2` to other models. The output models will be in `output_models/finetune`. You may load that model with `./scripts/run_chatbot.sh output/models/finetune` to have a chat with the finetuned model.

To specifying the dataset, you may change [this line](https://github.com/OptimalScale/LMFlow/blob/main/scripts/run_finetune.sh#L16) to the path of your customized dataset `/path-to-your-dataset/*.json`. The data format of `*.json` is provided in [dataset section of README](https://github.com/OptimalScale/LMFlow#2prepare-dataset), where `text_only` format can be used for training decoder-only models.

Our guide is available in [README](https://github.com/OptimalScale/LMFlow/blob/main/README.md). You are also welcomed to join [our community](https://lmflow.com/) for more information. Thanks 😄

**Comment by research4pan** [comment]
Thanks for providing more information! We have planned to support THUDM/chatglm-6b in [this pull request](https://github.com/OptimalScale/LMFlow/pull/152), but haven't merged it yet. We will let you know once it is officially supported. Thanks! 🙏

**Comment by fengsxy** [comment]
> Thanks for providing more information! We have planned to support THUDM/chatglm-6b in [this pull request](https://github.com/OptimalScale/LMFlow/pull/152), but haven't merged it yet. We will let you know once it is officially supported. Thanks! 🙏

I have reviewed the Code about Chatglm supporting, i think the core  is to add the args about `trust_remote_code=True`
but i found the code only supported in inferencing not in finetuneing. And if i want fine-tune now, is it possible just add args about ``trust_remote_code=True`.

**Comment by vincent7f** [comment]
@fengsxy  @research4pan 

I have a quick fix to support `trust_remote_code=True`. All you need is to add a new line (line 215, trust_remote_code = True) to file LMFlow/src/lmflow/models/hf_decoder_model.py . Check the capture for details.

![image](https://user-images.githubusercontent.com/45114756/232083510-4514995c-01d3-4739-9405-b0a2fe8d3de9.png)

**Comment by research4pan** [comment]
Thanks for your meaningful contribution! We will add this to our pull requests soon @shizhediao  😄 👍

**Comment by shizhediao** [comment]
Hi,
We are happy that ChatGLM inference is supported in our framework.
Please try this script: https://github.com/OptimalScale/LMFlow/blob/main/scripts/run_chatbot_chatglm.sh

**Comment by shizhediao** [comment]
Closed this issue.
If you have any further questions, please re-open it or create a new issue.

Thank you!
