### ISSUE TITLE
[BUG]运行./scripts/run_finetune.sh报如下错误，一直卡这。还有请问你们torch是pip intsall -e安装还是手动到官网安装呢。求求你们帮我看看吧，我要疯了。

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#446]
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! A quick fix is to remove the following section in `configs/ds_config_zero3.json`:

```
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
```

DeepSpeed uses a nvcc/c++ version of adam to speed up the optimization, which requires a compilation process and may sometimes fail due to wrong version of nvcc/c++. To find the exact problem that causes this issue, could you please provide the full log of error message, so we could check that for you?

As for installation of torch, by following `https://github.com/OptimalScale/LMFlow#1setup`, torch should be automatically installed. Thanks!  😄

**Comment by ShiXiangXiang123** [comment]
已经解决了，谢谢回复。
我的显卡驱动使用的nvidia-driver-530，cuda使用的11.7.0系列，cudnn使用的11.x系列。
有个极端做法但是不推荐，我出现“DeepSpeedCPUAdam”对象没有属性“ds_opt_adam”-》这个问题都是在普通用户下操作的，后来我用root安装在根目录解决了这个问题，用root用户来操作一切解决了。

**Comment by seanxuu** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/368#issuecomment-1552310311

我用的这个方法也ok
