### ISSUE TITLE
网页版 好像 所答非所问

### ISSUE THREAD

**Issue by alexhmyang** [OptimalScale/LMFlow#50]
![image](https://user-images.githubusercontent.com/10215059/229353107-5d0b02bf-a163-41d0-bec0-4347a0ed8b16.png)

http://lmflow.com/chat

**Comment by SHUMKASHUN** [comment]
Thank you for your interest in LMFlow ! This is due to the low-quality of public data we used currently for instruction tuning which only perform good on a specific set of instruction-tuned questions. The quality of training data is important, for example, our task-tuned LLaMA-7B can outperform ChatGPT in medical domain by training with the high quality medical datasets.

**Comment by research4pan** [comment]
Yeah, the quality of dataset is very important. We strongly recommend you to further finetuning the model with your own dataset, which may further improve the model performance. We are working on that as well. Thanks for your attention! 😄

**Comment by wangdelta** [comment]
老哥你英文拼写实在是有点堪忧..

**Comment by alexhmyang** [comment]
> 老哥你英文拼写实在是有点堪忧

好吧 哈哈
