### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fakerybakery** [OptimalScale/LMFlow#714]
Hi!
Thank you so much for releasing this awesome repository! I saw that at the bottom it says it's Apache licensed but we need to get authorization to use commercially, does this only apply if we're hosting it (as a service) or does it also apply to models? For example, if I train a model with this code, can I use it commercially or open-source it and allow others to use it commercially?
Thank you!

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! This claim only applies to models, since some models don't allow commercial usage (like llama-1), so their permissions should be obtained separately. For LMFlow, we don't have such restrictions, so as long as the model can be used commercially, you may use LMFlow to do the fine-tuning and inference for both commercial and research purposes.

Thanks 😄

**Comment by fakerybakery** [comment]
Thank you! Then we do not need to fill out the Google form in the License section if we want to open source the model and allow commercial usage?

**Comment by research4pan** [comment]
If it is not required by the model then yes. Our LMFlow team allows free and commercial usage of our framework 😄

**Comment by fakerybakery** [comment]
Cool, thanks! So I only need to fill out the “ Request Access to Commercial or Public Deployment of LMFlow” form if I am using LLaMA or another similarly licensed model?

**Comment by research4pan** [comment]
It depends on the model provider's policy. For LLaMA, you may check this [link](https://ai.meta.com/llama/license/) for its detailed license.

For LMFlow, we do not require filling of any form, so you can use LMFlow at your convenience 😄

**Comment by fakerybakery** [comment]
Thanks! Sorry, I’m a bit confused. It says in the README file that for commercial/public use you need to fill out that form, which is provided by LMFlow?

**Comment by research4pan** [comment]
Oh I see. This form is for surveying purposes, where we could provide your company with better support if you need one later. The code is totally free, and for the model, since we fine-tuned Robin is based on llama, which was only research-purpose about a half year ago (but now it has a different license), so we required this form.

In short, if you are using the code now, filling the form is just optional. Hope that can be helpful 😄

**Comment by fakerybakery** [comment]
Ah, makes sense. Thanks!
