### ISSUE TITLE
Why is the run_chatbot.sh not working properly?

### ISSUE THREAD

**Issue by xf4fresh** [OptimalScale/LMFlow#78]
I downloaded model(`llama7b-lora-380k`)，and run `run_chatbot.sh` with below commands:
`./scripts/run_chatbot.sh decapoda-research/llama-7b-hf ./output_models/llama7b-lora-380k`

![image](https://user-images.githubusercontent.com/24436845/229446563-1177f362-5b63-4ec7-a0d7-91506fc04dc0.png)

It appears to have started normally. But when I talk to it, it doesn't output what I expect.
Can anyone explain where is the problem?

Using default model(`gpt2`) also has error:
![image](https://user-images.githubusercontent.com/24436845/229451855-9c553dc8-0d06-4696-bfd9-7ac4c2f05ba4.png)

**Comment by research4pan** [comment]
Thanks for your attention! Our Chinese support for llama-7b is still improving. The current issue is mainly due to the low dataset quality we used for finetuning (not much Chinese in that dataset). As for GPT-2, this performance problem is expected, since GPT-2 is a rather weak model (much weaker than GPT-neo-2.7B).

To obtain a chatbot with satisfactory results, you can finetune a model in your own high quality dataset. We are working on that as well. Thanks for your interest 😄
