### ISSUE TITLE
LMFlow not support NVIDIA driver 11070?

### ISSUE THREAD

**Issue by 13416157913** [OptimalScale/LMFlow#798]
![image](https://github.com/OptimalScale/LMFlow/assets/20581199/bfe6fb7c-bad6-4c97-9450-832942f42567)

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! You may use LMFlow `<=v0.0.5` to resolve this problem as a temporary solution.

This issue is majorly caused by the dependency chain of `transformers` <- `pytorch` <- `cuda`. To use the latest model supported by `transformers`, one need the latest `transformers`, which normally requires `torch >= 2.0.0`. And this version of torch commonly requires a higher cuda version.

It is highly recommended to install cuda >= 12.0 to support latest `transformers`. Hope this information can be helpful 😄

**Comment by 13416157913** [comment]
> Thanks for your interest in LMFlow! You may use LMFlow `<=v0.0.5` to resolve this problem as a temporary solution.
> 
> This issue is majorly caused by the dependency chain of `transformers` <- `pytorch` <- `cuda`. To use the latest model supported by `transformers`, one need the latest `transformers`, which normally requires `torch >= 2.0.0`. And this version of torch commonly requires a higher cuda version.
> 
> It is highly recommended to install cuda >= 12.0 to support latest `transformers`. Hope this information can be helpful 😄

execute conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia 
the problem solved.
