### ISSUE TITLE
Hello，Where is the script run_finetune_with_lora_save_aggregated_weights.sh？Why I can't find it in LMFlow/scripts ?

### ISSUE THREAD

**Issue by 13416157913** [OptimalScale/LMFlow#799]
<img width="565" alt="企业微信截图_171439137015" src="https://github.com/OptimalScale/LMFlow/assets/20581199/6dccacec-4bf7-4df6-b03e-dc02a4d64537">

**Comment by research4pan** [comment]
Thanks for the valuable suggestion! You may find this script in `https://github.com/OptimalScale/LMFlow/blob/4459b46cf55cebeb59dd44fc4c87768dfdf99518/scripts/run_finetune_with_lora_save_aggregated_weights.sh`. We removed it since we found that OOM may occur at the end of training, so we decide to decouple the lora/qlora training logics and the aggregation logics, which are currently integrating into the repo.

We will remove this section of `README` temporarily and add the comment again once the feature is ready. Thanks for pointing that out 😄

**Comment by 13416157913** [comment]
> We will remove this section of `README` temporarily and add the comment again once the feature is ready. Thanks for pointing that out

Thanks for your answer.
