### ISSUE TITLE
find two problems in the codebase

### ISSUE THREAD

**Issue by Ch4osMy7h** [OptimalScale/LMFlow#96]
1. It seems text2text format do not supported by the tokenize function of model. In `hf_decoder_model.py` file, tokenize_function only encode the `first column` of dataset, which means the `"output" column` is ignored.
2. when I set `disable_group_texts=True`, I find that in the 146 line of finetuner.py file, `"total_length = (total_length // block_size) * block_size"`, if i have a sequence smaller than block_size, it will result the `total_length=0`, which ignore the example.

**Comment by research4pan** [comment]
Thanks for your suggestion! Those problems will be improved/fixed in the future.

For the first problem, currently we only support "text_only" for decoder-only models. Thus the behaviors for "text2text" + decoder only models are actually undefined. This is the part of code we leave for forward-compatibility and will be supported in the future.

For the second problem, we are already working on that. We expect the behavior of `disable_group_texts=True` to be padding, not truncation.

Hope this answers your question. If you have further suggestions about the codebase, please don't hesitate to contact us. We appreciate every constructive advice and contribution. Also, we strongly encourage you to participate in the construction of this codebase. Let's improve the framework and benefit everyone 😄

**Comment by shizhediao** [comment]
Hi,
We are glad to share that `text2text` format has been well-supported for now.
Please check it out.
Thanks!

**Comment by zwhe99** [comment]
@shizhediao @research4pan How to disable group text? I set disable_group_texts=True, and get the following error
<img width="757" alt="image" src="https://github.com/OptimalScale/LMFlow/assets/33388552/793782aa-74cf-43ba-84f3-e9c84c036cef">
